// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mwazovzky/microservices-introduction/product-api/swagger-codegen/models"
)

// ShowProductReader is a Reader for the ShowProduct structure.
type ShowProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowProductOK creates a ShowProductOK with default headers values
func NewShowProductOK() *ShowProductOK {
	return &ShowProductOK{}
}

/* ShowProductOK describes a response with status code 200, with default header values.

A list of products
*/
type ShowProductOK struct {
	Payload []*models.Product
}

func (o *ShowProductOK) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] showProductOK  %+v", 200, o.Payload)
}
func (o *ShowProductOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *ShowProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
