// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShowProductParams creates a new ShowProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShowProductParams() *ShowProductParams {
	return &ShowProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShowProductParamsWithTimeout creates a new ShowProductParams object
// with the ability to set a timeout on a request.
func NewShowProductParamsWithTimeout(timeout time.Duration) *ShowProductParams {
	return &ShowProductParams{
		timeout: timeout,
	}
}

// NewShowProductParamsWithContext creates a new ShowProductParams object
// with the ability to set a context for a request.
func NewShowProductParamsWithContext(ctx context.Context) *ShowProductParams {
	return &ShowProductParams{
		Context: ctx,
	}
}

// NewShowProductParamsWithHTTPClient creates a new ShowProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewShowProductParamsWithHTTPClient(client *http.Client) *ShowProductParams {
	return &ShowProductParams{
		HTTPClient: client,
	}
}

/* ShowProductParams contains all the parameters to send to the API endpoint
   for the show product operation.

   Typically these are written to a http.Request.
*/
type ShowProductParams struct {

	/* ID.

	   The id of the product for which the operation relates

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the show product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowProductParams) WithDefaults() *ShowProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the show product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the show product params
func (o *ShowProductParams) WithTimeout(timeout time.Duration) *ShowProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show product params
func (o *ShowProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show product params
func (o *ShowProductParams) WithContext(ctx context.Context) *ShowProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show product params
func (o *ShowProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show product params
func (o *ShowProductParams) WithHTTPClient(client *http.Client) *ShowProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show product params
func (o *ShowProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the show product params
func (o *ShowProductParams) WithID(id int64) *ShowProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the show product params
func (o *ShowProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ShowProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
